"""
Django settings for task_manager project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import psycopg2
import os
import sys
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-0ts1mc9#i*6hvkfpu2-am9pd-)##uf!iv^i!@8=tv#es)wu_m)"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = (os.environ.get("DEBUG", "False").lower() == "true")

ALLOWED_HOSTS = [
    "webserver",
    "127.0.0.1",
    "localhost",
    "python-project-52-q37n.onrender.com",
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "task_manager",
    "task_manager.users.apps.UsersConfig",
    "task_manager.statuses.apps.StatusesConfig",
    "task_manager.labels.apps.LabelsConfig",
    "django_filters",
    "task_manager.task.apps.TaskConfig"
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "rollbar.contrib.django.middleware.RollbarNotifierMiddleware" ,
]

ROOT_URLCONF = "task_manager.urls"

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "task_manager.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

import dj_database_url

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

db_url = os.getenv("DATABASE_URL")

if db_url:
    try:
        # 1. Пробуем подключиться к Postgres за 2 секунды
        # Это не даст Django "зависнуть" или упасть при старте
        conn = psycopg2.connect(db_url, connect_timeout=2)
        conn.close()

        # 2. Если успешно — применяем конфиг Postgres
        postgres_config = dj_database_url.config(
            default=db_url,
            conn_max_age=600,
            conn_health_checks=True
        )
        DATABASES['default'] = dict(postgres_config)
        print("🚀 Connected to PostgreSQL")
        
    except Exception as e:
        # Если Postgres выключен (status down), работаем на SQLite
        print(f"⚠️ Postgres connection failed: {e}")
        print("🏠 Using SQLite fallback")

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
#    {
#        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
#    },
#    {
#       "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
#   },
#    {
#       "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
#   },
#   {
#       "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
#   },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "ru-ru"

TIME_ZONE = "UTC"

USE_I18N = True

USE_10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

LOGIN_URL = 'login'
STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles_collected")


ROLLBAR = { 
    'access_token': os.getenv('ROLLBAR_ACCESS_TOKEN'),
    'environment' : 'development' if DEBUG else 'production' ,   
    'code_version' : '1.0' , 
    'root' : BASE_DIR ,
}

if 'test' in sys.argv:
    # 1. Полностью обнуляем настройки Rollbar
    ROLLBAR = {}
    
    # 2. Удаляем мидлвару Rollbar, чтобы она даже не пыталась запуститься
    if 'rollbar.contrib.django.middleware.RollbarNotifierMiddleware' in MIDDLEWARE:
        MIDDLEWARE.remove('rollbar.contrib.django.middleware.RollbarNotifierMiddleware')