# Generated by Django 6.0.1 on 2026-01-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('task', '0002_remove_task_label_task_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='label',
            field=models.ManyToManyField(blank=True, related_name='tasks_with_label', to='labels.label', verbose_name='Метки'),
        ),
    ]
